### ISSUE TITLE
Roadmap: A MVP

### ISSUE THREAD

**Issue by dawnofmidnight** [cat-dev-group/meow.c#4]
Meow is well... not exactly in existence just yet. This issue exists to track the steps needed to get an MVP (Minimum Viable Product) out there for use. PRs will be linked here as they are created.
You may notice that this takes are rather incremental approach. That's because it's much easier to write code that you can properly test and work with.
Note that this roadmap does not include everything, and will be edited as time passes. Also, things beyond the implementation of a basic VM may happen out of order. 

- [ ] Write the lexer (on demand)
- [ ] Write the AST
- [ ] Write a basic parser (Pratt style)
- [ ] Write a basic VM
- [ ] Add strings (as a much more complex data type then just numbers and the like, we wish to make sure that they are properly implemented)
- [ ] Add hashmaps
- [ ] Add variables
- [ ] Add functions (Call stack, compiler stack, call frames)
- [ ] Add classes
- [ ] Add interfaces
- [ ] Add enums
- [ ] Add error system (this is partly tied in with the actor step, as our runtime error philosophy is modeled after that of Erlang, which is "let it die and start a new process when needed")
- [ ] Add module system
- [ ] Add basic stdlib (this will have a separate tracking issue when the time comes, as it's a rather large endeavor)
- [ ] Start on concurrency (actors)
